version: '3.8'

services:
  # ==================================
  # 1. 프론트엔드 (FE) - 핫 리로딩 적용
  # ==================================
  frontend:
    build:
      context: .
    container_name: frontend_container
    ports:
      - "8080:80"
    volumes:
      - ./Front-End:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - capstone
    platform: linux/arm64/v8  # ARM64 아키텍처 사용

  mysql:
    container_name: mysql_container
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "13333:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - capstone
    platform: linux/arm64/v8  # ARM64 아키텍처 사용

  backend:
    platform: linux/amd64 
    image: jhh0101/capstone:v1.0.15
    container_name: backend_container
    env_file:
      - .env
    ports:
      - "18888:8082"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=dev
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/capstone?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - mysql
    networks:
      - capstone
  

volumes:
  mysql_data:

networks:
  capstone:
    driver: bridge
